# Generated by Django 4.2.1 on 2023-05-07 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydb',
            old_name='Image',
            new_name='CatImage',
        ),
    ]
