# Generated by Django 4.2.1 on 2023-05-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_image_categorydb_catimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Select', models.CharField(blank=True, max_length=50, null=True)),
                ('Pname', models.CharField(blank=True, max_length=50, null=True)),
                ('Brand', models.CharField(blank=True, max_length=50, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Des', models.CharField(blank=True, max_length=100, null=True)),
                ('ProductImage', models.ImageField(blank=True, null=True, upload_to='Product')),
            ],
        ),
    ]
